npm install -g @angular/cli
npm install -g moment
npm install -g jquery
npm install -g typescript
npm install -g primeng
npm install -g @progress/kendo-ui
npm install -g bootstrap
npm install -g ngx-bootstrap
npm install -g gulp-cli
